resources:
  pipelines:
    - pipeline: buildPipeline            # Reference name (any name)
      source: azure-pipelines-ci         # 👈 Use your CI pipeline's name (NOT filename!)
      trigger: true                      # 👈 Auto-trigger when CI completes

trigger: none

pool:
  name: Default

stages:
- stage: Deploy
  displayName: "Deploy to Minikube"
  jobs:
  - job: DeployToMinikube
    displayName: "Minikube Deployment Job"
    steps:
    - script: |
        kubectl apply -f k8s/
      displayName: "Apply Kubernetes Manifests"
