trigger:
- master

pool:
  name: Default

variables:
  backendPath: 'backend'
  frontendPath: 'frontend'

stages:
- stage: Build_Backend
  jobs:
  - job: Backend
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd $(backendPath)
        npm install
        echo "✅ Backend build completed"
      displayName: 'Install & Build Backend'

- stage: Build_Frontend
  jobs:
  - job: Frontend
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd $(frontendPath)
        npm install
        echo "✅ Frontend build completed"
      displayName: 'Install & Build Frontend'
